name: Buildbot

# Контроль событий при которых будет сборка
on:
  # В нашем случае это push в ветку main
  push:
    tags:
        - "v*"
    branches: [ "main" ]
  pull_request:
    tags:
        - "v*"
    branches: [ "main" ]
  # Позволяет запускать этот рабочий процесс вручную на вкладке Actions
  workflow_dispatch:

# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно
jobs:
  build:
    #  Все будет работать на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания
    steps:
      - uses: actions/checkout@v3

      # Установка зависимостей
      - name: Install python3, grub-pc-bin, xorriso, mtools, git
        run: sudo apt install python3 grub-pc-bin xorriso mtools qemu-system-x86 

      # Установка SynapseOS
      - name: Install SynapseOS
        run: |
          git clone --depth 1 https://github.com/0Nera/SynapseOS.git
          ls
          cd SynapseOS/

      # Скачивание и установка i686-elf-tools
      - name: Download i686-elf-tools
        run: |
          wget -nv https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
          sudo unzip i686-elf-tools-linux.zip -d /usr/local
          rm i686-elf-tools-linux.zip
          
      # Скачивание и установка i686-elf-tools
      - name: Install limine
        run: |
          cd SynapseOS/
          git clone https://github.com/limine-bootloader/limine.git --branch=v3.0-branch-binary --depth=1
          
      # Запуск сборки
      - name: Run build
        run: |
          cd SynapseOS/
          python3 build.py kernel
          make -C limine
          mkdir -p iso_root
          cp -v isodir/bootkernel.elf limine.cfg limine/limine.sys \
                limine/limine-cd.bin limine/limine-cd-efi.bin iso_root/

          xorriso -as mkisofs -b limine-cd.bin \
                  -no-emul-boot -boot-load-size 4 -boot-info-table \
                  --efi-boot limine-cd-efi.bin \
                  -efi-boot-part --efi-boot-image --protective-msdos-label \
                  iso_root -o SynapseOS.iso

          ./limine/limine-deploy SynapseOS.iso

      # Публикация релиза
      - name: Publish
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Autobuild"
          files: |
            SynapseOS/LICENSE
            SynapseOS/SynapseOS.iso
